# Generated by Django 5.2.4 on 2025-08-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagin_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания отправки'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='date_first',
            field=models.DateTimeField(verbose_name='Дата и время первой отправки '),
        ),
    ]
